import PDFDocument from "pdfkit";
import fs from "node:fs";
import path from "node:path";
import { env } from "../config/env.js";

const BRAND = {
  navy: "#1a1a2e",
  gold: "#f5a623",
  goldDark: "#d98c0d",
  ink: "#24243a",
  muted: "#667085",
  line: "#e4e7ec",
  soft: "#f8f9fc",
  green: "#0f8a4b",
};

const ORG = "Asian Development Educational & Research Foundation";
const LOGO_PATH = path.resolve("src/assets/logo.jpeg");

const clean = (value, fallback = "-") => {
  if (value === null || value === undefined || value === "") return fallback;
  return String(value);
};

const formatDate = (value = new Date()) =>
  new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value));

const fileTitle = (title) => title.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase();

const setPdfHeaders = (res, title) => {
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="${fileTitle(title)}.pdf"`);
};

const pipeDoc = (res, title, options = {}) => {
  const doc = new PDFDocument({ margin: 48, size: "A4", ...options });
  setPdfHeaders(res, title);
  doc.pipe(res);
  return doc;
};

const drawHeader = (doc, title, subtitle = "") => {
  const { width } = doc.page;
  doc.rect(0, 0, width, 116).fill(BRAND.navy);
  doc.rect(0, 106, width, 10).fill(BRAND.gold);
  if (fs.existsSync(LOGO_PATH)) {
    doc.roundedRect(48, 24, 58, 58, 6).fill("#ffffff");
    doc.image(LOGO_PATH, 53, 29, { fit: [48, 48], align: "center", valign: "center" });
  }
  const textX = fs.existsSync(LOGO_PATH) ? 122 : 48;
  doc.fillColor(BRAND.gold).font("Helvetica-Bold").fontSize(10).text("UTKARSH ANNUAL SCHOLARSHIP PROGRAM", textX, 28, {
    characterSpacing: 0.8,
  });
  doc.fillColor("#ffffff").fontSize(14).text(ORG, textX, 48, { width: width - textX - 48 });
  doc.fillColor("#d7dae2").font("Helvetica").fontSize(9).text("www.aderf.co.in | info@aderf.co.in | 6203281935 / 9430249924", textX, 74, {
    width: width - textX - 48,
  });
  doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(24).text(title, 48, 138);
  if (subtitle) {
    doc.fillColor(BRAND.muted).font("Helvetica").fontSize(10).text(subtitle, 48, 168);
  }
  doc.moveTo(48, 190).lineTo(width - 48, 190).strokeColor(BRAND.line).stroke();
  doc.y = 212;
};

const drawFooter = (doc, note = "Generated by Utkarsh Scholarship Portal") => {
  const { width, height } = doc.page;
  doc.moveTo(48, height - 82).lineTo(width - 48, height - 82).strokeColor(BRAND.line).stroke();
  doc.fillColor(BRAND.muted).font("Helvetica").fontSize(8).text(note, 48, height - 68, {
    width: width - 96,
    align: "center",
  });
};

const detailRows = (doc, rows, x, y, options = {}) => {
  const labelWidth = options.labelWidth || 145;
  const valueWidth = options.valueWidth || 335;
  const minRowHeight = options.rowHeight || 30;
  let nextY = y;

  rows.forEach(([label, value]) => {
    doc.font("Helvetica-Bold").fontSize(8);
    const labelHeight = doc.heightOfString(label.toUpperCase(), { width: labelWidth - 18 });
    doc.font("Helvetica-Bold").fontSize(10);
    const valueHeight = doc.heightOfString(clean(value), { width: valueWidth - 14 });
    const rowHeight = Math.max(minRowHeight, labelHeight + 18, valueHeight + 18);

    doc.roundedRect(x, nextY, labelWidth + valueWidth, rowHeight, 4).fill(BRAND.soft);
    doc.fillColor(BRAND.muted).font("Helvetica-Bold").fontSize(8).text(label.toUpperCase(), x + 12, nextY + 9, {
      width: labelWidth - 18,
    });
    doc.fillColor(BRAND.ink).font("Helvetica-Bold").fontSize(10).text(clean(value), x + labelWidth, nextY + 8, {
      width: valueWidth - 14,
    });
    nextY += rowHeight + 7;
  });

  return nextY;
};

const twoColumnRows = (doc, rows, x, y) => {
  const gap = 14;
  const colWidth = (doc.page.width - x * 2 - gap) / 2;
  let nextY = y;

  for (let index = 0; index < rows.length; index += 2) {
    const pair = rows.slice(index, index + 2);
    const heights = pair.map((row) => {
      doc.font("Helvetica-Bold").fontSize(7.5);
      const labelHeight = doc.heightOfString(row[0].toUpperCase(), { width: colWidth - 24 });
      doc.font("Helvetica-Bold").fontSize(10);
      const valueHeight = doc.heightOfString(clean(row[1]), { width: colWidth - 24 });
      return Math.max(44, labelHeight + valueHeight + 22);
    });
    const rowHeight = Math.max(...heights);

    if (nextY + rowHeight > doc.page.height - 78) {
      doc.addPage();
      nextY = 58;
    }

    pair.forEach((row, offset) => {
      const targetX = offset === 0 ? x : x + colWidth + gap;
      doc.roundedRect(targetX, nextY, colWidth, rowHeight, 5).strokeColor(BRAND.line).stroke();
      doc.fillColor(BRAND.muted).font("Helvetica-Bold").fontSize(7.5).text(row[0].toUpperCase(), targetX + 12, nextY + 8, {
        width: colWidth - 24,
      });
      doc.fillColor(BRAND.ink).font("Helvetica-Bold").fontSize(10).text(clean(row[1]), targetX + 12, nextY + 23, {
        width: colWidth - 24,
      });
    });

    nextY += rowHeight + 10;
  }

  return nextY;
};

const applicationRows = (application) => {
  const profile = application.user.profile || {};
  return {
    profile,
    common: [
      ["Registration Number", application.registrationNumber],
      ["Student Name", application.user.name],
      ["Session", application.sessionYear],
      ["Application Status", application.status],
      ["Scholarship Amount", `Rs. ${application.scholarshipAmount}`],
      ["Generated On", formatDate()],
    ],
  };
};

export const streamSimplePdf = (res, title, rows) => {
  const doc = pipeDoc(res, title);
  drawHeader(doc, title, "Official document generated from the scholarship portal");
  detailRows(doc, rows, 58, doc.y, { labelWidth: 155, valueWidth: 330 });
  drawFooter(doc);
  doc.end();
};

const streamReceiptPdf = (res, application) => {
  const doc = pipeDoc(res, "Registration Receipt");
  const { profile, common } = applicationRows(application);
  drawHeader(doc, "Registration Receipt", "Acknowledgement of scholarship application registration");

  const cardY = doc.y;
  doc.roundedRect(48, cardY, 500, 74, 8).fill("#fff7e8");
  doc.fillColor(BRAND.goldDark).font("Helvetica-Bold").fontSize(9).text("APPLICATION RECEIVED", 66, cardY + 16, { width: 250 });
  doc.fillColor(BRAND.navy).fontSize(24).text(clean(application.registrationNumber, "Draft not submitted"), 66, cardY + 32, { width: 280 });
  doc.fillColor(BRAND.muted).font("Helvetica").fontSize(9).text(`Issued on ${formatDate(application.submittedAt || new Date())}`, 370, cardY + 37, {
    width: 145,
    align: "right",
  });
  doc.y = cardY + 104;

  const detailEndY = detailRows(doc, [
    ...common.slice(1, 5),
    ["School", profile.schoolName],
    ["District", profile.district],
  ], 58, doc.y, { labelWidth: 155, valueWidth: 330 });

  doc.fillColor(BRAND.muted).font("Helvetica").fontSize(9).text(
    "This receipt confirms that the student's application record exists in the Utkarsh Scholarship Portal. Final selection depends on document verification and merit review.",
    58,
    Math.min(detailEndY + 16, 610),
    { width: 480, align: "center" },
  );
  drawFooter(doc);
  doc.end();
};

const streamApplicationFormPdf = (res, application) => {
  const doc = pipeDoc(res, "Application Form");
  const { profile, common } = applicationRows(application);
  drawHeader(doc, "Application Form", "Student and academic details submitted for review");

  doc.fillColor(BRAND.navy).font("Helvetica-Bold").fontSize(13).text("Application Summary", 48, doc.y);
  let y = twoColumnRows(doc, common, 48, doc.y + 20);

  doc.fillColor(BRAND.navy).font("Helvetica-Bold").fontSize(13).text("Student Details", 48, y + 14);
  y = twoColumnRows(doc, [
    ["Father Name", profile.fatherName],
    ["Mother Name", profile.motherName],
    ["Gender", profile.gender],
    ["Date of Birth", profile.dateOfBirth ? formatDate(profile.dateOfBirth) : "-"],
    ["Mobile", application.user.mobile],
    ["Email", application.user.email],
  ], 48, y + 36);

  doc.fillColor(BRAND.navy).font("Helvetica-Bold").fontSize(13).text("Academic and Address Details", 48, y + 10);
  twoColumnRows(doc, [
    ["Current Class", profile.currentClass || "X"],
    ["School", profile.schoolName],
    ["Board", profile.educationBoard],
    ["Previous Percentage", profile.previousPercentage ? `${profile.previousPercentage}%` : "-"],
    ["Roll Number", profile.rollNumber],
    ["City / Village", profile.city],
    ["District", profile.district],
    ["State", profile.state],
    ["Pin Code", profile.pinCode],
    ["Address", profile.address],
  ], 48, y + 32);

  drawFooter(doc, "Applicant details are digitally recorded and subject to document verification.");
  doc.end();
};

const streamAdmitCardPdf = (res, application) => {
  const doc = pipeDoc(res, "Admit Card");
  const { profile } = applicationRows(application);
  drawHeader(doc, "Admit Card", "Scholarship assessment entry document");

  const cardY = doc.y;
  doc.roundedRect(48, cardY, 500, 94, 8).strokeColor(BRAND.gold).lineWidth(1.4).stroke();
  doc.fillColor(BRAND.navy).font("Helvetica-Bold").fontSize(21).text(clean(application.user.name), 70, cardY + 18, {
    width: 335,
    ellipsis: true,
  });
  doc.fillColor(BRAND.muted).font("Helvetica").fontSize(10).text(`Registration No: ${clean(application.registrationNumber, "Not submitted")}`, 70, cardY + 50, {
    width: 330,
  });
  doc.fillColor(BRAND.muted).text(`Session: ${application.sessionYear}`, 70, cardY + 68, { width: 330 });
  doc.roundedRect(430, cardY + 16, 78, 62, 5).strokeColor(BRAND.line).stroke();
  doc.fillColor(BRAND.muted).font("Helvetica-Bold").fontSize(8).text("PHOTO", 430, cardY + 42, {
    width: 78,
    align: "center",
  });
  doc.y = cardY + 128;

  let detailsEndY = detailRows(doc, [
    ["Assessment", "Utkarsh Scholarship Merit Assessment"],
    ["Date and Time", "To be notified by ADERF"],
    ["Mode", "Online / notified test link"],
    ["School", profile.schoolName],
    ["District", profile.district],
    ["Board", profile.educationBoard],
  ], 58, doc.y, { labelWidth: 150, valueWidth: 335 });

  if (detailsEndY + 98 > doc.page.height - 72) {
    doc.addPage();
    detailsEndY = 72;
  }
  doc.fillColor(BRAND.navy).font("Helvetica-Bold").fontSize(12).text("Instructions", 58, detailsEndY + 12);
  [
    "Keep this admit card and registration number ready for all assessment communication.",
    "Use the same verified email and mobile number submitted in the application.",
    "ADERF may cancel candidature if details or uploaded documents are found incorrect.",
  ].forEach((item, index) => {
    doc.fillColor(BRAND.ink).font("Helvetica").fontSize(9).text(`${index + 1}. ${item}`, 58, detailsEndY + 34 + index * 18, {
      width: 480,
    });
  });

  drawFooter(doc);
  doc.end();
};

const streamSelectionLetterPdf = (res, application) => {
  const doc = pipeDoc(res, "Selection Letter");
  const { profile } = applicationRows(application);
  drawHeader(doc, "Selection Letter", "Official communication for selected scholarship candidates");

  doc.fillColor(BRAND.muted).font("Helvetica").fontSize(10).text(`Date: ${formatDate()}`, 48, doc.y);
  doc.moveDown(2);
  doc.fillColor(BRAND.ink).font("Helvetica").fontSize(11).text(`Dear ${clean(application.user.name, "Student")},`, {
    width: 500,
  });
  doc.moveDown(1);
  doc.fontSize(11).lineGap(5).text(
    `Congratulations. Based on the scholarship review process for academic session ${application.sessionYear}, your application has been marked ${application.status}. This letter records your selection status in the Utkarsh Annual Scholarship Program.`,
    { width: 500, align: "justify" },
  );
  doc.moveDown(1);
  doc.text(
    `The approved scholarship assistance for this program is Rs. ${application.scholarshipAmount}. Disbursement and any final formalities will be handled by ADERF after verification of required records.`,
    { width: 500, align: "justify" },
  );
  doc.moveDown(1.6);
  const rowsEndY = detailRows(doc, [
    ["Registration Number", application.registrationNumber],
    ["Student Name", application.user.name],
    ["School", profile.schoolName],
    ["District", profile.district],
    ["Session", application.sessionYear],
    ["Status", application.status],
  ], 58, doc.y, { labelWidth: 155, valueWidth: 330, rowHeight: 25 });

  const signatureY = Math.min(Math.max(rowsEndY + 34, 620), 684);
  doc.fillColor(BRAND.ink).font("Helvetica").fontSize(10).text("Authorized Signatory", 370, signatureY + 9);
  doc.moveTo(356, signatureY).lineTo(510, signatureY).strokeColor(BRAND.navy).stroke();
  drawFooter(doc, "This selection letter is valid only with matching portal records.");
  doc.end();
};

const streamCertificateFallbackPdf = (res, application) => {
  const doc = pipeDoc(res, "Scholarship Certificate", { margin: 36, layout: "landscape" });
  const { profile } = applicationRows(application);
  const { width, height } = doc.page;

  doc.rect(0, 0, width, height).fill("#fffdf8");
  doc.rect(24, 24, width - 48, height - 48).lineWidth(4).strokeColor(BRAND.gold).stroke();
  doc.rect(38, 38, width - 76, height - 76).lineWidth(1).strokeColor(BRAND.navy).stroke();
  doc.fillColor(BRAND.navy).font("Helvetica-Bold").fontSize(17).text(ORG, 60, 70, { align: "center", width: width - 120 });
  doc.fillColor(BRAND.goldDark).fontSize(36).text("Certificate of Scholarship", 60, 138, {
    align: "center",
    width: width - 120,
  });
  doc.fillColor(BRAND.muted).font("Helvetica").fontSize(14).text("This certificate is proudly presented to", 60, 218, {
    align: "center",
    width: width - 120,
  });
  doc.fillColor(BRAND.navy).font("Helvetica-Bold").fontSize(31).text(clean(application.user.name), 60, 254, {
    align: "center",
    width: width - 120,
  });
  doc.fillColor(BRAND.ink).font("Helvetica").fontSize(13).text(
    `for being selected as an Utkarsh Scholar for academic session ${application.sessionYear}.`,
    90,
    318,
    { align: "center", width: width - 180 },
  );
  doc.fillColor(BRAND.muted).fontSize(11).text(
    `School: ${clean(profile.schoolName)} | District: ${clean(profile.district)} | Award: Rs. ${application.scholarshipAmount}`,
    90,
    350,
    { align: "center", width: width - 180 },
  );
  doc.fillColor(BRAND.ink).font("Helvetica-Bold").fontSize(10).text(`Registration No: ${clean(application.registrationNumber)}`, 72, 500);
  doc.text(`Generated On: ${formatDate()}`, 72, 518);
  doc.moveTo(width - 235, 508).lineTo(width - 80, 508).strokeColor(BRAND.navy).stroke();
  doc.text("Authorized Signatory", width - 225, 518);
  doc.end();
};

export const streamStudentDocumentPdf = (res, kind, application) => {
  const template = {
    receipt: streamReceiptPdf,
    application: streamApplicationFormPdf,
    "admit-card": streamAdmitCardPdf,
    "selection-letter": streamSelectionLetterPdf,
    certificate: streamCertificateFallbackPdf,
  }[kind];

  if (template) {
    template(res, application);
    return;
  }

  streamSimplePdf(res, "Utkarsh Document", [
    ["Registration Number", application.registrationNumber],
    ["Student Name", application.user.name],
    ["Session", application.sessionYear],
    ["Status", application.status],
  ]);
};

export const streamResultSheetPdf = (res, sessionYear, results) => {
  const doc = pipeDoc(res, `utkarsh-results-${sessionYear}`, { margin: 42 });
  drawHeader(doc, "Selected Scholars Result", `Academic Session: ${sessionYear}`);

  const startX = 42;
  const widths = [34, 104, 126, 142, 70, 56];
  const headers = ["S.No", "Reg. No.", "Student", "School", "District", "Status"];
  let y = doc.y;

  const drawRow = (cells, bold = false) => {
    let x = startX;
    const rowHeight = bold ? 30 : 38;
    doc.roundedRect(startX, y - 6, widths.reduce((a, b) => a + b, 0), rowHeight, bold ? 6 : 0)
      .fill(bold ? "#fff7e8" : "#ffffff");
    doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(8.5).fillColor(bold ? BRAND.navy : BRAND.ink);
    cells.forEach((cell, index) => {
      doc.text(clean(cell), x + 5, y + (bold ? 4 : 0), { width: widths[index] - 8, height: rowHeight - 4 });
      x += widths[index];
    });
    y += rowHeight;
    doc.moveTo(startX, y - 6).lineTo(startX + widths.reduce((a, b) => a + b, 0), y - 6).strokeColor(BRAND.line).stroke();
  };

  drawRow(headers, true);
  results.forEach((result, index) => {
    const profile = result.application.user.profile || {};
    drawRow([
      index + 1,
      result.application.registrationNumber,
      result.application.user.name,
      profile.schoolName,
      profile.district,
      result.status,
    ]);
  });

  if (!results.length) {
    doc.roundedRect(72, y + 24, 452, 86, 8).fill(BRAND.soft);
    doc.fillColor(BRAND.navy).font("Helvetica-Bold").fontSize(13).text("No published selected scholars found", 92, y + 48, {
      width: 412,
      align: "center",
    });
    doc.fillColor(BRAND.muted).font("Helvetica").fontSize(10).text(
      "Results will appear here after ADERF publishes the selected candidates for this academic session.",
      92,
      y + 72,
      { width: 412, align: "center" },
    );
  }

  drawFooter(doc, "This result sheet is generated from the official Utkarsh Scholarship Portal.");
  doc.end();
};

export const createCertificatePdf = async (application, certificateNo) => {
  const generatedDir = path.resolve(env.UPLOAD_DIR, "generated");
  fs.mkdirSync(generatedDir, { recursive: true });
  const fileName = `${certificateNo}.pdf`;
  const filePath = path.join(generatedDir, fileName);
  const publicUrl = `${env.PUBLIC_UPLOAD_URL}/generated/${fileName}`;

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 36, size: "A4", layout: "landscape" });
    const stream = fs.createWriteStream(filePath);
    stream.on("finish", resolve);
    stream.on("error", reject);
    doc.pipe(stream);

    const profile = application.user.profile || {};
    const { width, height } = doc.page;
    doc.rect(0, 0, width, height).fill("#fffdf8");
    doc.rect(24, 24, width - 48, height - 48).lineWidth(4).strokeColor(BRAND.gold).stroke();
    doc.rect(38, 38, width - 76, height - 76).lineWidth(1).strokeColor(BRAND.navy).stroke();
    doc.fillColor(BRAND.navy).font("Helvetica-Bold").fontSize(17).text(ORG, 60, 70, { align: "center", width: width - 120 });
    doc.fillColor(BRAND.goldDark).fontSize(36).text("Certificate of Scholarship", 60, 138, {
      align: "center",
      width: width - 120,
    });
    doc.fillColor(BRAND.muted).font("Helvetica").fontSize(14).text("This certificate is proudly presented to", 60, 218, {
      align: "center",
      width: width - 120,
    });
    doc.fillColor(BRAND.navy).font("Helvetica-Bold").fontSize(31).text(application.user.name, 60, 254, {
      align: "center",
      width: width - 120,
    });
    doc.fillColor(BRAND.ink).font("Helvetica").fontSize(13).text(
      `for being selected as an Utkarsh Scholar for academic session ${application.sessionYear}.`,
      90,
      318,
      { align: "center", width: width - 180 },
    );
    doc.fillColor(BRAND.muted).fontSize(11).text(
      `School: ${clean(profile.schoolName)} | District: ${clean(profile.district)} | Award: Rs. ${application.scholarshipAmount}`,
      90,
      350,
      { align: "center", width: width - 180 },
    );
    doc.fillColor(BRAND.ink).font("Helvetica-Bold").fontSize(10).text(`Certificate ID: ${certificateNo}`, 72, 500);
    doc.text(`Registration No: ${clean(application.registrationNumber)}`, 72, 518);
    doc.moveTo(width - 235, 508).lineTo(width - 80, 508).strokeColor(BRAND.navy).stroke();
    doc.text("Authorized Signatory", width - 225, 518);
    doc.end();
  });

  return { filePath, publicUrl };
};
